### ISSUE TITLE
write limit

### ISSUE THREAD

**Issue by mehrdad987** [blackcodetavern/ESP32_FTPClient#3]
it does not write large file
Are there restrictions defined for this part

void ESP32_FTPClient::Write(const char * str) {
  FTPdbgn(F("Write File"));
  if(!isConnected()) return;
  
  GetDataClient()->print(str);
}
//////////
String jib = fie.readString();//READ FROM SD
ftp.Write(jib.c_str());//WRITE TO FILE IN SERVER

**Comment by blackcodetavern** [comment]
I also encountered this, when I tried to upload my large Images.
Thats why I wrote the WriteData method. This method uses a Buffer to
write the data in chunks to the server. In my case I couldn't even allocate 
enough space at once on the microcontroller, because the images were too large.

**Comment by mehrdad987** [comment]
there is another thing that I think is necessary
I made a file in my FTP server and i write data every hour to file but it's not possible to append yet
after I write data on a same file its not appended

**Comment by blackcodetavern** [comment]
Appending is possible, in my example I make this, and it appends to the file:
ftp.InitFile("Type A");
ftp.AppendFile("hello_world_append.txt");
ftp.Write("Hello World");
ftp.CloseFile();

Did you try the combination of AppendFile and WriteData?

**Comment by mehrdad987** [comment]
yep its creat a file and it's not appending on a file
it might be  sth wrong with my writing
it is not appending data on a file
        ftp.OpenConnection();
        ftp.ChangeWorkDir(working_dir);
        initializeSD();
        //ftp.InitFile("Type A");
        //ftp.NewFile("test.txt");
	  ftp.InitFile("Type A");
	  ftp.AppendFile("test.txt");
        openFile((char*) temp.c_str());
        Serial.println((char*) temp.c_str()); 
        int counter = 0;
        while (counter < 60){
          String bermoda = (readLine());
          counter++;
          Serial.println(bermoda);
          Serial.println(counter);
          ftp.Write((char*)bermoda.c_str());
        }
        closeFile();
        ftp.CloseFile();
