### ISSUE TITLE
Issue when overwritting the same file

### ISSUE THREAD

**Issue by benny007** [blackcodetavern/ESP32_FTPClient#9]
Hi,

Thanks for the work on this library.

I'm trying to use it to overwrite the same file again and again to a FTP server in the same stream (that is without closing the connection because it has to be very fast and closing the file, reopening it and closing and reopening the connection add a huge delay).

However the file on my server is not properly overwritten it just keeps on growing instead.

Any thought if this expected or if there is something that can be done ?

Thanks.

**Comment by blackcodetavern** [comment]
Can you show the code of how you write into the file?

**Comment by blackcodetavern** [comment]
Couldn't you just operate on a string and only write it to the server from time to time, e.g. when there is a request for the file. Whatever you do it might be much faster this way.

**Comment by benny007** [comment]
Something like this:

void setup(){
ftp.OpenConnection();
ftp.InitFile("Type I");
ftp.ChangeWorkDir("/stream");
ftp.NewFile("photo.jpg");
}

void loop{
stream();
}

void stream(void){
cam.run();
ftp.WriteData(cam.getfb(), cam.getSize());
}

So it's actually taking the picture from the camera and uploading it to the FTP server, over and over again to stream it through a single .jpg file. But doing it this way result in having a growing file in my FTP server instead of overwritten it. It's like there is nothing saying it's the end of the file.

And if I use the NewFile()/CloseFile() in the stream function this trigger a new connection every time hence producing a huge delay.

Cheers

**Comment by blackcodetavern** [comment]
The WriteData method appends data to the image file. I don't think there is a way to improve this.
Maybe you can reduce the lag, if you write the data in a file "photo_tmp.jpg" and than rename the file to "photo.jpg". Than again create a file "photo_tmp.jpg", I had a similar issue some time ago. My server was somehow slow when overwriting an existing file.

But if you are looking for a faster method, you should maybe look into websockets.
